# Generated by Django 2.2.5 on 2020-04-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='cpu_type',
            field=models.CharField(choices=[('single', 'Single-core'), ('dual', 'Dual-core'), ('quad', 'Quad-core'), ('hexa', 'Hexa-core'), ('octa', 'Octa-core')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='mc_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('dual', 'Dual'), ('triple', 'Triple'), ('triple+', 'Triple+')], max_length=20, null=True, verbose_name='Main Camera Type'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='sc_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('dual', 'Dual'), ('triple', 'Triple'), ('triple+', 'Triple+')], max_length=20, null=True, verbose_name='Selfie Camera Type'),
        ),
    ]
