# Generated by Django 2.2.5 on 2020-04-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200425_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='announced_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='released_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
