# Generated by Django 2.2.5 on 2020-04-24 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200425_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='ram',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='storage',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
