# Generated by Django 2.2.5 on 2020-04-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200425_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephone',
            name='is_wkp',
            field=models.BooleanField(default=False, verbose_name='Is Phone of the week?'),
        ),
    ]
