# Generated by Django 2.2.5 on 2020-04-25 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200425_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='listings.Brand'),
        ),
    ]
