# Generated by Django 2.2.5 on 2020-04-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20200425_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephone',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
