# Generated by Django 2.2.5 on 2020-04-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_mobilephone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephone',
            name='likes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
