# Generated by Django 2.2.5 on 2020-05-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
