# Generated by Django 2.2.5 on 2020-05-20 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20200520_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='listings.Comment'),
        ),
    ]
