# Generated by Django 2.2.5 on 2020-05-20 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20200520_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='phone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='listings.MobilePhone'),
        ),
    ]
