# Generated by Django 2.2.5 on 2020-05-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20200520_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephone',
            name='reviews',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
