# Generated by Django 2.2.5 on 2020-05-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20200521_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikes',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='listings.Comment'),
        ),
        migrations.AlterField(
            model_name='phonelikes',
            name='phone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='listings.MobilePhone'),
        ),
        migrations.AlterField(
            model_name='phonereviews',
            name='phone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.MobilePhone'),
        ),
    ]
