# Generated by Django 2.2.5 on 2020-05-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20200522_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
