# Generated by Django 2.2.5 on 2020-05-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20200522_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='weight',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
