# Generated by Django 2.2.5 on 2020-05-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_auto_20200522_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='weight',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
